
GET http://localhost:3000/users/get
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjc5MzA5MTk4fQ.wDkkdq39e7v6QzGo2TWBspjWA73iuXef3pIl3mBW4do


###



POST http://localhost:3000/auth/login
Content-Type:application/json

{
	"email": "rishavinmngo@gmail.com",
	"password": "123456789"

}




####

POST http://localhost:3000/auth/register
Content-Type:application/json

{
	"displayName": "vikram raj",
	"email": "vikram@gmail.com",
	"password": "123456789",
	"organisation_id": 3,
	"is_organisation": false
}

###


GET http://localhost:3000/users/getAllDoctors
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjc5MzA5MTk4fQ.wDkkdq39e7v6QzGo2TWBspjWA73iuXef3pIl3mBW4do




###

GET http://localhost:3000/department/getAll
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgwMTE2MDU5fQ.QFpaIPTYTLVSe_esWnZ28VOwAWKCSqPtJF5VshRm3gA

###

POST http://localhost:3000/department/add
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjc5MzA5MTk4fQ.wDkkdq39e7v6QzGo2TWBspjWA73iuXef3pIl3mBW4do
Content-Type:application/json

{
	"name": "department of cardiologist"
}




###

GET http://localhost:3000/patients/getAll
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjc5MzA5MTk4fQ.wDkkdq39e7v6QzGo2TWBspjWA73iuXef3pIl3mBW4do



###
POST http://localhost:3000/patients/add
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjc5MzA5MTk4fQ.wDkkdq39e7v6QzGo2TWBspjWA73iuXef3pIl3mBW4do
Content-Type:application/json

{
	"name": "rina",
	"age": 21,
	"gender": "f"
	}



###


PUT http://localhost:3000/department/update
Content-Type: application/json

{
		"name":"Department of physics"
}


####


DELETE http://localhost:3000/department/delete
Content-Type: application/json

{
		"id": 1
}



####

POST http://localhost:3000/appointments/add
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjgwMDkwNzcwfQ.AxGdLCPaw-S-1DUa_tdQTRni_rtoja86RJe_NLa1Skw
Content-Type: application/json

{
		"doctors_id": 15,
		"patients_id": 4
}




###



GET http://localhost:3000/appointments/getAll
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjgwMDkwNzcwfQ.AxGdLCPaw-S-1DUa_tdQTRni_rtoja86RJe_NLa1Skw




####

POST http://localhost:3000/appointments/getAllByDate
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjgwMDkwNzcwfQ.AxGdLCPaw-S-1DUa_tdQTRni_rtoja86RJe_NLa1Skw
Content-Type: application/json

{
	"date": "2023-03-28"
}


###



POST http://localhost:3000/appointments/getByDoctor
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjgwMDkwNzcwfQ.AxGdLCPaw-S-1DUa_tdQTRni_rtoja86RJe_NLa1Skw
Content-Type: application/json

{
	"doctors_id": 15 
}



####


POST http://localhost:3000/appointments/getByDoctorAndDate
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjgwMDkwNzcwfQ.AxGdLCPaw-S-1DUa_tdQTRni_rtoja86RJe_NLa1Skw
Content-Type: application/json

{
	"doctors_id": 15 ,
	"date": "2023-03-28"
}




#####




GET http://localhost:3000/users/has/phy
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjgwMDkwNzcwfQ.AxGdLCPaw-S-1DUa_tdQTRni_rtoja86RJe_NLa1Skw






###
GET http://localhost:3000/prescription/medicine/getAll/7
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgzMjcxMDA2fQ.Ft-qIFgszRVjjCVJeJyJagFoIAmSLJpJj-o_Bi3StBQ


###


POST http://localhost:3000/prescription/medicine/add/7
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgzMjcxMDA2fQ.Ft-qIFgszRVjjCVJeJyJagFoIAmSLJpJj-o_Bi3StBQ
Content-Type:application/json

{
"medicine_id": 10625,
"dosage": "1 day 1 night",
"duration": "10 days"
}

PUT http://localhost:3000/prescription/medicine/update/7
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgzMjcxMDA2fQ.Ft-qIFgszRVjjCVJeJyJagFoIAmSLJpJj-o_Bi3StBQ
Content-Type:application/json

{
	"id": 4,
"medicine_id": 10631,
"dosage": "2 day 1 night",
"duration": "0 days"
}

DELETE http://localhost:3000/prescription/medicine/delete/5
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgzMjcxMDA2fQ.Ft-qIFgszRVjjCVJeJyJagFoIAmSLJpJj-o_Bi3StBQ


GET http://localhost:3000/inventory/medicine/has/re
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjgzOTExMjkzfQ.m6OCaBqLrfJYpbES-7YJKQq4ckYpZgqZg8baFWTQNLQ



GET http://localhost:3000/prescription/prescribedMedicine/getAll/8
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgzODA5MTc3fQ.T5Hwhykq3cY45-VGV4hITKytC3VGrOGdZ1MtWOiY2Nk



GET http://localhost:3000/prescription/medicine/getAll/8
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgzODA5MTc3fQ.T5Hwhykq3cY45-VGV4hITKytC3VGrOGdZ1MtWOiY2Nk


GET http://localhost:3000/prescription/advice/getAll/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgzODA5MTc3fQ.T5Hwhykq3cY45-VGV4hITKytC3VGrOGdZ1MtWOiY2Nk


####



POST http://localhost:3000/prescription/advice/add/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgzODA5MTc3fQ.T5Hwhykq3cY45-VGV4hITKytC3VGrOGdZ1MtWOiY2Nk
Content-Type:application/json

{
"advice":"kuch v karo par thik ho jao"
}




####

PUT http://localhost:3000/prescription/advice/update/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgzODA5MTc3fQ.T5Hwhykq3cY45-VGV4hITKytC3VGrOGdZ1MtWOiY2Nk
Content-Type:application/json

{
	"id":5,
"advice":"Go to Gym"
}

####
DELETE http://localhost:3000/prescription/advice/delete/4
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgzODA5MTc3fQ.T5Hwhykq3cY45-VGV4hITKytC3VGrOGdZ1MtWOiY2Nk


GET http://localhost:3000/users/getDoctorById/6
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgzODA5MTc3fQ.T5Hwhykq3cY45-VGV4hITKytC3VGrOGdZ1MtWOiY2Nk
