
GET http://localhost:3000/users/get
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjc5MzA5MTk4fQ.wDkkdq39e7v6QzGo2TWBspjWA73iuXef3pIl3mBW4do


###



POST http://localhost:3000/auth/login
Content-Type:application/json

{
	"email": "rishavinmngo@gmail.com",
	"password": "123456789"

}




####

POST http://localhost:3000/auth/register
Content-Type:application/json

{
	"displayName": "vikram raj",
	"email": "vikram@gmail.com",
	"password": "123456789",
	"organisation_id": 3,
	"is_organisation": false
}

###


GET http://localhost:3000/users/getAllDoctors
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjc5MzA5MTk4fQ.wDkkdq39e7v6QzGo2TWBspjWA73iuXef3pIl3mBW4do




###

GET http://localhost:3000/department/getAll
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjc5MzA5MTk4fQ.wDkkdq39e7v6QzGo2TWBspjWA73iuXef3pIl3mBW4do


###

POST http://localhost:3000/department/add
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjc5MzA5MTk4fQ.wDkkdq39e7v6QzGo2TWBspjWA73iuXef3pIl3mBW4do
Content-Type:application/json

{
	"name": "department of cardiologist"
}




###

GET http://localhost:3000/patients/getAll
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjc5MzA5MTk4fQ.wDkkdq39e7v6QzGo2TWBspjWA73iuXef3pIl3mBW4do



###
POST http://localhost:3000/patients/add
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjc5MzA5MTk4fQ.wDkkdq39e7v6QzGo2TWBspjWA73iuXef3pIl3mBW4do
Content-Type:application/json

{
	"name": "rahul",
	"age": 22,
	"gender": "m"
	}
